name: Test GitHub Secret

on:
  push:
    branches:
      - main

jobs:
  test_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print secret
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}"
